[book]
title = "Pico Pico - Embedded Programming with Rust"
authors = ["ImplFerris"]
language = "en"
src = "src"

[output.html]
git-repository-url = "https://github.com/ImplFerris/pico-pico"
cname = "pico.implrust.com"
preferred-dark-theme = "ayu"
default-theme = "light"
mathjax-support = true
sidebar-header-nav = false
additional-css = ["theme/css/custom.css"]
additional-js = ["theme/js/navigation.js"]

[output.html.fold]
enable = true
level = 1

[output.html.playground]
editable = true

[output.html.redirect]
"/led/pwm-rp2350.html" = "/core-concepts/pwm/pwm-in-rp2350.html"
"/servo/pwm.html" = "/servo/how-servo-works.html"
"/servo/servo.html" = "/servo/index.html"
